
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ksusha
    password: Sdfghjky1!

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: false