server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:ksusha}
    password: ${POSTGRES_PASSWORD:Sdfghjky1!}

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: false