name: Build

on:
  pull_request:
    branches:
      - 'feature/devops'

  push:
    branches:
      - 'feature/devops'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Maven Package
        run: mvn -B clean package -DskipTestsTOKEN }}